/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { HasInitializer } from "../HasInitializer";

export class HasInitializer__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<HasInitializer> {
    return super.deploy(overrides || {}) as Promise<HasInitializer>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): HasInitializer {
    return super.attach(address) as HasInitializer;
  }
  connect(signer: Signer): HasInitializer__factory {
    return super.connect(signer) as HasInitializer__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HasInitializer {
    return new Contract(address, _abi, signerOrProvider) as HasInitializer;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550603f80605d6000396000f3fe6080604052600080fdfea2646970667358221220d3c722e89d953a0f4e88e25baa04a3c46e3a2253dd52000fe60ebbe8b2c8953764736f6c63430007060033";
