/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IVoteCounter } from "../IVoteCounter";

export class IVoteCounter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVoteCounter {
    return new Contract(address, _abi, signerOrProvider) as IVoteCounter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
