/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CommitmentMinterInterface extends ethers.utils.Interface {
  functions: {
    "commitmentToken()": FunctionFragment;
    "stableReserves()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "commitmentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stableReserves",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "commitmentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stableReserves",
    data: BytesLike
  ): Result;

  events: {};
}

export class CommitmentMinter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CommitmentMinterInterface;

  functions: {
    commitmentToken(overrides?: CallOverrides): Promise<[string]>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<[string]>;

    stableReserves(overrides?: CallOverrides): Promise<[string]>;

    "stableReserves()"(overrides?: CallOverrides): Promise<[string]>;
  };

  commitmentToken(overrides?: CallOverrides): Promise<string>;

  "commitmentToken()"(overrides?: CallOverrides): Promise<string>;

  stableReserves(overrides?: CallOverrides): Promise<string>;

  "stableReserves()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    commitmentToken(overrides?: CallOverrides): Promise<string>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<string>;

    stableReserves(overrides?: CallOverrides): Promise<string>;

    "stableReserves()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    commitmentToken(overrides?: CallOverrides): Promise<BigNumber>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    stableReserves(overrides?: CallOverrides): Promise<BigNumber>;

    "stableReserves()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    commitmentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "commitmentToken()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stableReserves(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "stableReserves()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
