/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface CryptoJobBoardInterface extends ethers.utils.Interface {
  functions: {
    "accpetableTokens(address)": FunctionFragment;
    "addAndExecuteBudget(uint256,address,uint256,bytes)": FunctionFragment;
    "addBudget(uint256,address,uint256)": FunctionFragment;
    "addCurrency(address)": FunctionFragment;
    "anarchize()": FunctionFragment;
    "anarchizedAt()": FunctionFragment;
    "approveProject(uint256)": FunctionFragment;
    "approvedProjects(uint256)": FunctionFragment;
    "baseCurrency()": FunctionFragment;
    "closeProject(uint256)": FunctionFragment;
    "commitmentFund()": FunctionFragment;
    "createProject(string,string,string)": FunctionFragment;
    "disapproveProject(uint256)": FunctionFragment;
    "executeBudget(uint256,uint256,bytes)": FunctionFragment;
    "forceAnarchize()": FunctionFragment;
    "forceAnarchizeAt()": FunctionFragment;
    "forceApproveBudget(uint256,uint256)": FunctionFragment;
    "funds(address)": FunctionFragment;
    "getTotalBudgets(uint256)": FunctionFragment;
    "gov()": FunctionFragment;
    "managers(address)": FunctionFragment;
    "normalTaxRate()": FunctionFragment;
    "oneInch()": FunctionFragment;
    "project()": FunctionFragment;
    "projectBudgets(uint256,uint256)": FunctionFragment;
    "removeCurrency(address)": FunctionFragment;
    "setAnarchyPoint(uint256)": FunctionFragment;
    "setExchange(address)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setManager(address,bool)": FunctionFragment;
    "setTaxRate(uint256)": FunctionFragment;
    "setTaxRateForUndeclared(uint256)": FunctionFragment;
    "taxRateForUndeclared()": FunctionFragment;
    "taxToVisionFarm(address,uint256)": FunctionFragment;
    "taxations(address)": FunctionFragment;
    "visionFarm()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accpetableTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAndExecuteBudget",
    values: [BigNumberish, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addBudget",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "addCurrency", values: [string]): string;
  encodeFunctionData(functionFragment: "anarchize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anarchizedAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedProjects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "baseCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentFund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disapproveProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBudget",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceAnarchize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceAnarchizeAt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forceApproveBudget",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "funds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTotalBudgets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(functionFragment: "managers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "normalTaxRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oneInch", values?: undefined): string;
  encodeFunctionData(functionFragment: "project", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectBudgets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurrency",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAnarchyPoint",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setExchange", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setManager",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setTaxRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTaxRateForUndeclared",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taxRateForUndeclared",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taxToVisionFarm",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "taxations", values: [string]): string;
  encodeFunctionData(
    functionFragment: "visionFarm",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accpetableTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAndExecuteBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addBudget", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "anarchize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "anarchizedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disapproveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceAnarchize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceAnarchizeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceApproveBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "funds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBudgets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "managers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "normalTaxRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oneInch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "project", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectBudgets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAnarchyPoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExchange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTaxRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTaxRateForUndeclared",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxRateForUndeclared",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taxToVisionFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taxations", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "visionFarm", data: BytesLike): Result;

  events: {
    "Anarchized()": EventFragment;
    "BudgetAdded(uint256,uint256,address,uint256)": EventFragment;
    "BudgetExecuted(uint256,uint256)": EventFragment;
    "BudgetWithdrawn(uint256,uint256)": EventFragment;
    "ManagerUpdated(address,bool)": EventFragment;
    "NewGovernance(address,address)": EventFragment;
    "ProjectClosed(uint256)": EventFragment;
    "ProjectPosted(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Anarchized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BudgetAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BudgetExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BudgetWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ManagerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewGovernance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProjectClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProjectPosted"): EventFragment;
}

export class CryptoJobBoard extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CryptoJobBoardInterface;

  functions: {
    accpetableTokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "accpetableTokens(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    addAndExecuteBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addAndExecuteBudget(uint256,address,uint256,bytes)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addBudget(uint256,address,uint256)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "addCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    anarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "anarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    anarchizedAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    "anarchizedAt()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    approveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "approveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approvedProjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "approvedProjects(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    baseCurrency(overrides?: CallOverrides): Promise<[string]>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<[string]>;

    closeProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "closeProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commitmentFund(overrides?: CallOverrides): Promise<[string]>;

    "commitmentFund()"(overrides?: CallOverrides): Promise<[string]>;

    createProject(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createProject(string,string,string)"(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    disapproveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "disapproveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeBudget(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "executeBudget(uint256,uint256,bytes)"(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceAnarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "forceAnarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceAnarchizeAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    "forceAnarchizeAt()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    forceApproveBudget(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "forceApproveBudget(uint256,uint256)"(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    funds(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "funds(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTotalBudgets(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getTotalBudgets(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    gov(overrides?: CallOverrides): Promise<[string]>;

    "gov()"(overrides?: CallOverrides): Promise<[string]>;

    managers(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "managers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    normalTaxRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "normalTaxRate()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    oneInch(overrides?: CallOverrides): Promise<[string]>;

    "oneInch()"(overrides?: CallOverrides): Promise<[string]>;

    project(overrides?: CallOverrides): Promise<[string]>;

    "project()"(overrides?: CallOverrides): Promise<[string]>;

    projectBudgets(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean] & {
        currency: string;
        amount: BigNumber;
        transferred: boolean;
      }
    >;

    "projectBudgets(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean] & {
        currency: string;
        amount: BigNumber;
        transferred: boolean;
      }
    >;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "removeCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAnarchyPoint(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setAnarchyPoint(uint256)"(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setExchange(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setExchange(address)"(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGovernance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setGovernance(address)"(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setManager(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setManager(address,bool)"(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTaxRate(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTaxRate(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTaxRateForUndeclared(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setTaxRateForUndeclared(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    taxRateForUndeclared(overrides?: CallOverrides): Promise<[BigNumber]>;

    "taxRateForUndeclared()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    taxToVisionFarm(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "taxToVisionFarm(address,uint256)"(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    taxations(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "taxations(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    visionFarm(overrides?: CallOverrides): Promise<[string]>;

    "visionFarm()"(overrides?: CallOverrides): Promise<[string]>;
  };

  accpetableTokens(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "accpetableTokens(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  addAndExecuteBudget(
    projId: BigNumberish,
    token: string,
    amount: BigNumberish,
    swapData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addAndExecuteBudget(uint256,address,uint256,bytes)"(
    projId: BigNumberish,
    token: string,
    amount: BigNumberish,
    swapData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addBudget(
    projId: BigNumberish,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addBudget(uint256,address,uint256)"(
    projId: BigNumberish,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addCurrency(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "addCurrency(address)"(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  anarchize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "anarchize()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  anarchizedAt(overrides?: CallOverrides): Promise<BigNumber>;

  "anarchizedAt()"(overrides?: CallOverrides): Promise<BigNumber>;

  approveProject(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "approveProject(uint256)"(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approvedProjects(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "approvedProjects(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  baseCurrency(overrides?: CallOverrides): Promise<string>;

  "baseCurrency()"(overrides?: CallOverrides): Promise<string>;

  closeProject(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "closeProject(uint256)"(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commitmentFund(overrides?: CallOverrides): Promise<string>;

  "commitmentFund()"(overrides?: CallOverrides): Promise<string>;

  createProject(
    title: string,
    description: string,
    URI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createProject(string,string,string)"(
    title: string,
    description: string,
    URI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  disapproveProject(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "disapproveProject(uint256)"(
    projId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeBudget(
    projId: BigNumberish,
    index: BigNumberish,
    swapData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "executeBudget(uint256,uint256,bytes)"(
    projId: BigNumberish,
    index: BigNumberish,
    swapData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceAnarchize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "forceAnarchize()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceAnarchizeAt(overrides?: CallOverrides): Promise<BigNumber>;

  "forceAnarchizeAt()"(overrides?: CallOverrides): Promise<BigNumber>;

  forceApproveBudget(
    projId: BigNumberish,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "forceApproveBudget(uint256,uint256)"(
    projId: BigNumberish,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  funds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "funds(address)"(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  getTotalBudgets(
    projId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalBudgets(uint256)"(
    projId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  gov(overrides?: CallOverrides): Promise<string>;

  "gov()"(overrides?: CallOverrides): Promise<string>;

  managers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "managers(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  normalTaxRate(overrides?: CallOverrides): Promise<BigNumber>;

  "normalTaxRate()"(overrides?: CallOverrides): Promise<BigNumber>;

  oneInch(overrides?: CallOverrides): Promise<string>;

  "oneInch()"(overrides?: CallOverrides): Promise<string>;

  project(overrides?: CallOverrides): Promise<string>;

  "project()"(overrides?: CallOverrides): Promise<string>;

  projectBudgets(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, boolean] & {
      currency: string;
      amount: BigNumber;
      transferred: boolean;
    }
  >;

  "projectBudgets(uint256,uint256)"(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, boolean] & {
      currency: string;
      amount: BigNumber;
      transferred: boolean;
    }
  >;

  removeCurrency(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "removeCurrency(address)"(
    currency: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAnarchyPoint(
    timestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setAnarchyPoint(uint256)"(
    timestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setExchange(
    _oneInch: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setExchange(address)"(
    _oneInch: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGovernance(
    _gov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setGovernance(address)"(
    _gov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setManager(
    manager: string,
    active: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setManager(address,bool)"(
    manager: string,
    active: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTaxRate(
    rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTaxRate(uint256)"(
    rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTaxRateForUndeclared(
    rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setTaxRateForUndeclared(uint256)"(
    rate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  taxRateForUndeclared(overrides?: CallOverrides): Promise<BigNumber>;

  "taxRateForUndeclared()"(overrides?: CallOverrides): Promise<BigNumber>;

  taxToVisionFarm(
    currency: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "taxToVisionFarm(address,uint256)"(
    currency: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  taxations(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "taxations(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  visionFarm(overrides?: CallOverrides): Promise<string>;

  "visionFarm()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    accpetableTokens(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "accpetableTokens(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addAndExecuteBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "addAndExecuteBudget(uint256,address,uint256,bytes)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "addBudget(uint256,address,uint256)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addCurrency(currency: string, overrides?: CallOverrides): Promise<void>;

    "addCurrency(address)"(
      currency: string,
      overrides?: CallOverrides
    ): Promise<void>;

    anarchize(overrides?: CallOverrides): Promise<void>;

    "anarchize()"(overrides?: CallOverrides): Promise<void>;

    anarchizedAt(overrides?: CallOverrides): Promise<BigNumber>;

    "anarchizedAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    approveProject(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "approveProject(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    approvedProjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "approvedProjects(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    baseCurrency(overrides?: CallOverrides): Promise<string>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<string>;

    closeProject(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "closeProject(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    commitmentFund(overrides?: CallOverrides): Promise<string>;

    "commitmentFund()"(overrides?: CallOverrides): Promise<string>;

    createProject(
      title: string,
      description: string,
      URI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "createProject(string,string,string)"(
      title: string,
      description: string,
      URI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    disapproveProject(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "disapproveProject(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeBudget(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeBudget(uint256,uint256,bytes)"(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    forceAnarchize(overrides?: CallOverrides): Promise<void>;

    "forceAnarchize()"(overrides?: CallOverrides): Promise<void>;

    forceAnarchizeAt(overrides?: CallOverrides): Promise<BigNumber>;

    "forceAnarchizeAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    forceApproveBudget(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "forceApproveBudget(uint256,uint256)"(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    funds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "funds(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalBudgets(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalBudgets(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<string>;

    "gov()"(overrides?: CallOverrides): Promise<string>;

    managers(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "managers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    normalTaxRate(overrides?: CallOverrides): Promise<BigNumber>;

    "normalTaxRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    oneInch(overrides?: CallOverrides): Promise<string>;

    "oneInch()"(overrides?: CallOverrides): Promise<string>;

    project(overrides?: CallOverrides): Promise<string>;

    "project()"(overrides?: CallOverrides): Promise<string>;

    projectBudgets(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean] & {
        currency: string;
        amount: BigNumber;
        transferred: boolean;
      }
    >;

    "projectBudgets(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, boolean] & {
        currency: string;
        amount: BigNumber;
        transferred: boolean;
      }
    >;

    removeCurrency(currency: string, overrides?: CallOverrides): Promise<void>;

    "removeCurrency(address)"(
      currency: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAnarchyPoint(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAnarchyPoint(uint256)"(
      timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setExchange(_oneInch: string, overrides?: CallOverrides): Promise<void>;

    "setExchange(address)"(
      _oneInch: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernance(_gov: string, overrides?: CallOverrides): Promise<void>;

    "setGovernance(address)"(
      _gov: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setManager(
      manager: string,
      active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setManager(address,bool)"(
      manager: string,
      active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setTaxRate(rate: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "setTaxRate(uint256)"(
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTaxRateForUndeclared(
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setTaxRateForUndeclared(uint256)"(
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    taxRateForUndeclared(overrides?: CallOverrides): Promise<BigNumber>;

    "taxRateForUndeclared()"(overrides?: CallOverrides): Promise<BigNumber>;

    taxToVisionFarm(
      currency: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "taxToVisionFarm(address,uint256)"(
      currency: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    taxations(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "taxations(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    visionFarm(overrides?: CallOverrides): Promise<string>;

    "visionFarm()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    Anarchized(): TypedEventFilter<[], {}>;

    BudgetAdded(
      projId: BigNumberish | null,
      index: null,
      token: null,
      amount: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      { projId: BigNumber; index: BigNumber; token: string; amount: BigNumber }
    >;

    BudgetExecuted(
      projId: null,
      index: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { projId: BigNumber; index: BigNumber }
    >;

    BudgetWithdrawn(
      projId: null,
      index: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { projId: BigNumber; index: BigNumber }
    >;

    ManagerUpdated(
      manager: string | null,
      active: null
    ): TypedEventFilter<
      [string, boolean],
      { manager: string; active: boolean }
    >;

    NewGovernance(
      _prevGovernance: string | null,
      _newGovernance: string | null
    ): TypedEventFilter<
      [string, string],
      { _prevGovernance: string; _newGovernance: string }
    >;

    ProjectClosed(
      projId: null
    ): TypedEventFilter<[BigNumber], { projId: BigNumber }>;

    ProjectPosted(
      projId: null
    ): TypedEventFilter<[BigNumber], { projId: BigNumber }>;
  };

  estimateGas: {
    accpetableTokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "accpetableTokens(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addAndExecuteBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addAndExecuteBudget(uint256,address,uint256,bytes)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addBudget(uint256,address,uint256)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "addCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    anarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "anarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    anarchizedAt(overrides?: CallOverrides): Promise<BigNumber>;

    "anarchizedAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    approveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "approveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approvedProjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "approvedProjects(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseCurrency(overrides?: CallOverrides): Promise<BigNumber>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<BigNumber>;

    closeProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "closeProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commitmentFund(overrides?: CallOverrides): Promise<BigNumber>;

    "commitmentFund()"(overrides?: CallOverrides): Promise<BigNumber>;

    createProject(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createProject(string,string,string)"(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    disapproveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "disapproveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeBudget(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "executeBudget(uint256,uint256,bytes)"(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceAnarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "forceAnarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceAnarchizeAt(overrides?: CallOverrides): Promise<BigNumber>;

    "forceAnarchizeAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    forceApproveBudget(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "forceApproveBudget(uint256,uint256)"(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    funds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "funds(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalBudgets(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalBudgets(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<BigNumber>;

    "gov()"(overrides?: CallOverrides): Promise<BigNumber>;

    managers(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "managers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    normalTaxRate(overrides?: CallOverrides): Promise<BigNumber>;

    "normalTaxRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    oneInch(overrides?: CallOverrides): Promise<BigNumber>;

    "oneInch()"(overrides?: CallOverrides): Promise<BigNumber>;

    project(overrides?: CallOverrides): Promise<BigNumber>;

    "project()"(overrides?: CallOverrides): Promise<BigNumber>;

    projectBudgets(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "projectBudgets(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "removeCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAnarchyPoint(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setAnarchyPoint(uint256)"(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setExchange(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setExchange(address)"(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGovernance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setGovernance(address)"(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setManager(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setManager(address,bool)"(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTaxRate(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTaxRate(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTaxRateForUndeclared(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setTaxRateForUndeclared(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    taxRateForUndeclared(overrides?: CallOverrides): Promise<BigNumber>;

    "taxRateForUndeclared()"(overrides?: CallOverrides): Promise<BigNumber>;

    taxToVisionFarm(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "taxToVisionFarm(address,uint256)"(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    taxations(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "taxations(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    visionFarm(overrides?: CallOverrides): Promise<BigNumber>;

    "visionFarm()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accpetableTokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "accpetableTokens(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addAndExecuteBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addAndExecuteBudget(uint256,address,uint256,bytes)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addBudget(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addBudget(uint256,address,uint256)"(
      projId: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "addCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    anarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "anarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    anarchizedAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "anarchizedAt()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "approveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approvedProjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "approvedProjects(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseCurrency(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    closeProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "closeProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commitmentFund(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "commitmentFund()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createProject(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createProject(string,string,string)"(
      title: string,
      description: string,
      URI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    disapproveProject(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "disapproveProject(uint256)"(
      projId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeBudget(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "executeBudget(uint256,uint256,bytes)"(
      projId: BigNumberish,
      index: BigNumberish,
      swapData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceAnarchize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "forceAnarchize()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceAnarchizeAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "forceAnarchizeAt()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    forceApproveBudget(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "forceApproveBudget(uint256,uint256)"(
      projId: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    funds(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "funds(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalBudgets(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalBudgets(uint256)"(
      projId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gov()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    managers(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "managers(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    normalTaxRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "normalTaxRate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oneInch(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oneInch()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    project(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "project()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    projectBudgets(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "projectBudgets(uint256,uint256)"(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCurrency(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "removeCurrency(address)"(
      currency: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAnarchyPoint(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setAnarchyPoint(uint256)"(
      timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setExchange(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setExchange(address)"(
      _oneInch: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setGovernance(address)"(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setManager(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setManager(address,bool)"(
      manager: string,
      active: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTaxRate(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTaxRate(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTaxRateForUndeclared(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setTaxRateForUndeclared(uint256)"(
      rate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    taxRateForUndeclared(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "taxRateForUndeclared()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    taxToVisionFarm(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "taxToVisionFarm(address,uint256)"(
      currency: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    taxations(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "taxations(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    visionFarm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "visionFarm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
