/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FarmersUnionInterface extends ethers.utils.Interface {
  functions: {
    "NO_DEPENDENCY()": FunctionFragment;
    "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)": FunctionFragment;
    "execute(address,uint256,bytes,bytes32,bytes32)": FunctionFragment;
    "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)": FunctionFragment;
    "getVotes(address)": FunctionFragment;
    "getVotingStatus(bytes32)": FunctionFragment;
    "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)": FunctionFragment;
    "hashTransaction(address,uint256,bytes,bytes32,bytes32)": FunctionFragment;
    "launch()": FunctionFragment;
    "memorandom()": FunctionFragment;
    "paused()": FunctionFragment;
    "proposals(bytes32)": FunctionFragment;
    "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)": FunctionFragment;
    "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)": FunctionFragment;
    "visionFarm()": FunctionFragment;
    "vote(bytes32,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "NO_DEPENDENCY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeMemorandom",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [string, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [string[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getVotes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getVotingStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashBatchTransaction",
    values: [string[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashTransaction",
    values: [string, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "launch", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "memorandom",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeBatchTx",
    values: [
      string[],
      BigNumberish[],
      BytesLike[],
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeTx",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "visionFarm",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "NO_DEPENDENCY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeMemorandom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVotingStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashBatchTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "launch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "memorandom", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeBatchTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposeTx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "visionFarm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;

  events: {
    "BatchTxProposed(bytes32,address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)": EventFragment;
    "Paused(address)": EventFragment;
    "ProposalExecuted(bytes32)": EventFragment;
    "TxProposed(bytes32,address,uint256,bytes,bytes32,bytes32,uint256,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Vote(bytes32,address,bool)": EventFragment;
    "VoteUpdated(bytes32,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BatchTxProposed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TxProposed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Vote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteUpdated"): EventFragment;
}

export class FarmersUnion extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FarmersUnionInterface;

  functions: {
    NO_DEPENDENCY(overrides?: CallOverrides): Promise<[string]>;

    "NO_DEPENDENCY()"(overrides?: CallOverrides): Promise<[string]>;

    changeMemorandom(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)"(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execute(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "execute(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeBatch(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getVotes(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getVotes(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getVotingStatus(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "getVotingStatus(bytes32)"(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    hashBatchTransaction(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hashTransaction(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "hashTransaction(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    launch(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "launch()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    memorandom(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        minimumPending: BigNumber;
        maximumPending: BigNumber;
        minimumVotingPeriod: BigNumber;
        maximumVotingPeriod: BigNumber;
        minimumVotesForProposing: BigNumber;
        minimumVotes: BigNumber;
        voteCounter: string;
      }
    >;

    "memorandom()"(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        minimumPending: BigNumber;
        maximumPending: BigNumber;
        minimumVotingPeriod: BigNumber;
        maximumVotingPeriod: BigNumber;
        minimumVotesForProposing: BigNumber;
        minimumVotes: BigNumber;
        voteCounter: string;
      }
    >;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    proposals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        proposer: string;
        start: BigNumber;
        end: BigNumber;
        totalForVotes: BigNumber;
        totalAgainstVotes: BigNumber;
        executed: boolean;
      }
    >;

    "proposals(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        proposer: string;
        start: BigNumber;
        end: BigNumber;
        totalForVotes: BigNumber;
        totalAgainstVotes: BigNumber;
        executed: boolean;
      }
    >;

    proposeBatchTx(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposeTx(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    visionFarm(overrides?: CallOverrides): Promise<[string]>;

    "visionFarm()"(overrides?: CallOverrides): Promise<[string]>;

    vote(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "vote(bytes32,bool)"(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  NO_DEPENDENCY(overrides?: CallOverrides): Promise<string>;

  "NO_DEPENDENCY()"(overrides?: CallOverrides): Promise<string>;

  changeMemorandom(
    minimumPendingPeriod: BigNumberish,
    maximumPendingPeriod: BigNumberish,
    minimumVotingPeriod: BigNumberish,
    maximumVotingPeriod: BigNumberish,
    minimumVotesForProposing: BigNumberish,
    minimumVotes: BigNumberish,
    voteCounter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)"(
    minimumPendingPeriod: BigNumberish,
    maximumPendingPeriod: BigNumberish,
    minimumVotingPeriod: BigNumberish,
    maximumVotingPeriod: BigNumberish,
    minimumVotesForProposing: BigNumberish,
    minimumVotes: BigNumberish,
    voteCounter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execute(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "execute(address,uint256,bytes,bytes32,bytes32)"(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeBatch(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getVotes(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getVotes(address)"(
    account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getVotingStatus(
    txHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  "getVotingStatus(bytes32)"(
    txHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  hashBatchTransaction(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)"(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  hashTransaction(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "hashTransaction(address,uint256,bytes,bytes32,bytes32)"(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  launch(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "launch()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  memorandom(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string
    ] & {
      minimumPending: BigNumber;
      maximumPending: BigNumber;
      minimumVotingPeriod: BigNumber;
      maximumVotingPeriod: BigNumber;
      minimumVotesForProposing: BigNumber;
      minimumVotes: BigNumber;
      voteCounter: string;
    }
  >;

  "memorandom()"(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string
    ] & {
      minimumPending: BigNumber;
      maximumPending: BigNumber;
      minimumVotingPeriod: BigNumber;
      maximumVotingPeriod: BigNumber;
      minimumVotesForProposing: BigNumber;
      minimumVotes: BigNumber;
      voteCounter: string;
    }
  >;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  proposals(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      proposer: string;
      start: BigNumber;
      end: BigNumber;
      totalForVotes: BigNumber;
      totalAgainstVotes: BigNumber;
      executed: boolean;
    }
  >;

  "proposals(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
      proposer: string;
      start: BigNumber;
      end: BigNumber;
      totalForVotes: BigNumber;
      totalAgainstVotes: BigNumber;
      executed: boolean;
    }
  >;

  proposeBatchTx(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    startsIn: BigNumberish,
    votingPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)"(
    target: string[],
    value: BigNumberish[],
    data: BytesLike[],
    predecessor: BytesLike,
    salt: BytesLike,
    startsIn: BigNumberish,
    votingPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposeTx(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    startsIn: BigNumberish,
    votingPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)"(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    salt: BytesLike,
    startsIn: BigNumberish,
    votingPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  visionFarm(overrides?: CallOverrides): Promise<string>;

  "visionFarm()"(overrides?: CallOverrides): Promise<string>;

  vote(
    txHash: BytesLike,
    agree: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "vote(bytes32,bool)"(
    txHash: BytesLike,
    agree: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    NO_DEPENDENCY(overrides?: CallOverrides): Promise<string>;

    "NO_DEPENDENCY()"(overrides?: CallOverrides): Promise<string>;

    changeMemorandom(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)"(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "execute(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    executeBatch(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getVotes(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getVotes(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotingStatus(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    "getVotingStatus(bytes32)"(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    hashBatchTransaction(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    hashTransaction(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "hashTransaction(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    launch(overrides?: CallOverrides): Promise<void>;

    "launch()"(overrides?: CallOverrides): Promise<void>;

    memorandom(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        minimumPending: BigNumber;
        maximumPending: BigNumber;
        minimumVotingPeriod: BigNumber;
        maximumVotingPeriod: BigNumber;
        minimumVotesForProposing: BigNumber;
        minimumVotes: BigNumber;
        voteCounter: string;
      }
    >;

    "memorandom()"(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        minimumPending: BigNumber;
        maximumPending: BigNumber;
        minimumVotingPeriod: BigNumber;
        maximumVotingPeriod: BigNumber;
        minimumVotesForProposing: BigNumber;
        minimumVotes: BigNumber;
        voteCounter: string;
      }
    >;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    proposals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        proposer: string;
        start: BigNumber;
        end: BigNumber;
        totalForVotes: BigNumber;
        totalAgainstVotes: BigNumber;
        executed: boolean;
      }
    >;

    "proposals(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, BigNumber, boolean] & {
        proposer: string;
        start: BigNumber;
        end: BigNumber;
        totalForVotes: BigNumber;
        totalAgainstVotes: BigNumber;
        executed: boolean;
      }
    >;

    proposeBatchTx(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    proposeTx(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    visionFarm(overrides?: CallOverrides): Promise<string>;

    "visionFarm()"(overrides?: CallOverrides): Promise<string>;

    vote(
      txHash: BytesLike,
      agree: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "vote(bytes32,bool)"(
      txHash: BytesLike,
      agree: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BatchTxProposed(
      txHash: BytesLike | null,
      target: null,
      value: null,
      data: null,
      predecessor: null,
      salt: null,
      start: null,
      end: null
    ): TypedEventFilter<
      [
        string,
        string[],
        BigNumber[],
        string[],
        string,
        string,
        BigNumber,
        BigNumber
      ],
      {
        txHash: string;
        target: string[];
        value: BigNumber[];
        data: string[];
        predecessor: string;
        salt: string;
        start: BigNumber;
        end: BigNumber;
      }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    ProposalExecuted(
      txHash: null
    ): TypedEventFilter<[string], { txHash: string }>;

    TxProposed(
      txHash: BytesLike | null,
      target: null,
      value: null,
      data: null,
      predecessor: null,
      salt: null,
      start: null,
      end: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, string, string, BigNumber, BigNumber],
      {
        txHash: string;
        target: string;
        value: BigNumber;
        data: string;
        predecessor: string;
        salt: string;
        start: BigNumber;
        end: BigNumber;
      }
    >;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;

    Vote(
      txHash: null,
      voter: null,
      forVote: null
    ): TypedEventFilter<
      [string, string, boolean],
      { txHash: string; voter: string; forVote: boolean }
    >;

    VoteUpdated(
      txHash: null,
      forVotes: null,
      againsVotes: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { txHash: string; forVotes: BigNumber; againsVotes: BigNumber }
    >;
  };

  estimateGas: {
    NO_DEPENDENCY(overrides?: CallOverrides): Promise<BigNumber>;

    "NO_DEPENDENCY()"(overrides?: CallOverrides): Promise<BigNumber>;

    changeMemorandom(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)"(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execute(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "execute(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeBatch(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getVotes(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getVotes(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotingStatus(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getVotingStatus(bytes32)"(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashBatchTransaction(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashTransaction(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hashTransaction(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    launch(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "launch()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    memorandom(overrides?: CallOverrides): Promise<BigNumber>;

    "memorandom()"(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposals(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "proposals(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeBatchTx(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposeTx(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    visionFarm(overrides?: CallOverrides): Promise<BigNumber>;

    "visionFarm()"(overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "vote(bytes32,bool)"(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NO_DEPENDENCY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "NO_DEPENDENCY()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeMemorandom(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "changeMemorandom(uint256,uint256,uint256,uint256,uint256,uint256,address)"(
      minimumPendingPeriod: BigNumberish,
      maximumPendingPeriod: BigNumberish,
      minimumVotingPeriod: BigNumberish,
      maximumVotingPeriod: BigNumberish,
      minimumVotesForProposing: BigNumberish,
      minimumVotes: BigNumberish,
      voteCounter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "execute(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeBatch(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getVotes(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVotes(address)"(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVotingStatus(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVotingStatus(bytes32)"(
      txHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashBatchTransaction(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hashBatchTransaction(address[],uint256[],bytes[],bytes32,bytes32)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashTransaction(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hashTransaction(address,uint256,bytes,bytes32,bytes32)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    launch(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "launch()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    memorandom(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "memorandom()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposals(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposals(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeBatchTx(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "proposeBatchTx(address[],uint256[],bytes[],bytes32,bytes32,uint256,uint256)"(
      target: string[],
      value: BigNumberish[],
      data: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposeTx(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "proposeTx(address,uint256,bytes,bytes32,bytes32,uint256,uint256)"(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      startsIn: BigNumberish,
      votingPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    visionFarm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "visionFarm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vote(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "vote(bytes32,bool)"(
      txHash: BytesLike,
      agree: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
