/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IStableReserveInterface extends ethers.utils.Interface {
  functions: {
    "baseCurrency()": FunctionFragment;
    "commitmentToken()": FunctionFragment;
    "reserveAndMint(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "baseCurrency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitmentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveAndMint",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "baseCurrency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitmentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveAndMint",
    data: BytesLike
  ): Result;

  events: {};
}

export class IStableReserve extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IStableReserveInterface;

  functions: {
    baseCurrency(overrides?: CallOverrides): Promise<[string]>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<[string]>;

    commitmentToken(overrides?: CallOverrides): Promise<[string]>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<[string]>;

    reserveAndMint(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "reserveAndMint(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  baseCurrency(overrides?: CallOverrides): Promise<string>;

  "baseCurrency()"(overrides?: CallOverrides): Promise<string>;

  commitmentToken(overrides?: CallOverrides): Promise<string>;

  "commitmentToken()"(overrides?: CallOverrides): Promise<string>;

  reserveAndMint(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "reserveAndMint(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    baseCurrency(overrides?: CallOverrides): Promise<string>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<string>;

    commitmentToken(overrides?: CallOverrides): Promise<string>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<string>;

    reserveAndMint(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "reserveAndMint(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    baseCurrency(overrides?: CallOverrides): Promise<BigNumber>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<BigNumber>;

    commitmentToken(overrides?: CallOverrides): Promise<BigNumber>;

    "commitmentToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    reserveAndMint(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "reserveAndMint(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    baseCurrency(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "baseCurrency()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    commitmentToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "commitmentToken()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserveAndMint(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "reserveAndMint(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
