/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ITokenEmitterInterface extends ethers.utils.Interface {
  functions: {
    "distribute()": FunctionFragment;
    "emissionPeriod()": FunctionFragment;
    "setEmissionPeriod(uint256)": FunctionFragment;
    "setWeight(uint256,uint256,uint256,uint256)": FunctionFragment;
    "start(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "distribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emissionPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmissionPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWeight",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "start",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emissionPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmissionPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWeight", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "start", data: BytesLike): Result;

  events: {};
}

export class ITokenEmitter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITokenEmitterInterface;

  functions: {
    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    emissionPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    "emissionPeriod()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    setEmissionPeriod(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setEmissionPeriod(uint256)"(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWeight(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setWeight(uint256,uint256,uint256,uint256)"(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    start(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "start(address,address)"(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  distribute(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "distribute()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  emissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  "emissionPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

  setEmissionPeriod(
    _emissionPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setEmissionPeriod(uint256)"(
    _emissionPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWeight(
    commit: BigNumberish,
    liquidity: BigNumberish,
    dev: BigNumberish,
    caller: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setWeight(uint256,uint256,uint256,uint256)"(
    commit: BigNumberish,
    liquidity: BigNumberish,
    dev: BigNumberish,
    caller: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  start(
    _liquidityMining: string,
    _commitMining: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "start(address,address)"(
    _liquidityMining: string,
    _commitMining: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    distribute(overrides?: CallOverrides): Promise<void>;

    "distribute()"(overrides?: CallOverrides): Promise<void>;

    emissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    "emissionPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

    setEmissionPeriod(
      _emissionPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setEmissionPeriod(uint256)"(
      _emissionPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setWeight(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setWeight(uint256,uint256,uint256,uint256)"(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    start(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "start(address,address)"(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    emissionPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    "emissionPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

    setEmissionPeriod(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setEmissionPeriod(uint256)"(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWeight(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setWeight(uint256,uint256,uint256,uint256)"(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    start(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "start(address,address)"(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    emissionPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "emissionPeriod()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setEmissionPeriod(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setEmissionPeriod(uint256)"(
      _emissionPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWeight(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setWeight(uint256,uint256,uint256,uint256)"(
      commit: BigNumberish,
      liquidity: BigNumberish,
      dev: BigNumberish,
      caller: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    start(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "start(address,address)"(
      _liquidityMining: string,
      _commitMining: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
