/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SquareRootVoteCounterInterface extends ethers.utils.Interface {
  functions: {
    "getVotes(address)": FunctionFragment;
    "visionFarm()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getVotes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "visionFarm",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "visionFarm", data: BytesLike): Result;

  events: {};
}

export class SquareRootVoteCounter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SquareRootVoteCounterInterface;

  functions: {
    getVotes(voter: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getVotes(address)"(
      voter: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    visionFarm(overrides?: CallOverrides): Promise<[string]>;

    "visionFarm()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getVotes(voter: string, overrides?: CallOverrides): Promise<BigNumber>;

  "getVotes(address)"(
    voter: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  visionFarm(overrides?: CallOverrides): Promise<string>;

  "visionFarm()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getVotes(voter: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getVotes(address)"(
      voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    visionFarm(overrides?: CallOverrides): Promise<string>;

    "visionFarm()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getVotes(voter: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getVotes(address)"(
      voter: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    visionFarm(overrides?: CallOverrides): Promise<BigNumber>;

    "visionFarm()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getVotes(
      voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVotes(address)"(
      voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    visionFarm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "visionFarm()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
