/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StakeMiningPoolFactoryInterface extends ethers.utils.Interface {
  functions: {
    "newPool(address,address,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "newPool",
    values: [string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "newPool", data: BytesLike): Result;

  events: {
    "NewStakeMiningPool(address,address,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewStakeMiningPool"): EventFragment;
}

export class StakeMiningPoolFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StakeMiningPoolFactoryInterface;

  functions: {
    newPool(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "newPool(address,address,address,address)"(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  newPool(
    _token: string,
    _emitter: string,
    _stakingToken: string,
    _recoverTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "newPool(address,address,address,address)"(
    _token: string,
    _emitter: string,
    _stakingToken: string,
    _recoverTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    newPool(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "newPool(address,address,address,address)"(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    NewStakeMiningPool(
      _token: null,
      _emitter: null,
      _stakingToken: null,
      _recoverTo: null,
      _poolAddress: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      {
        _token: string;
        _emitter: string;
        _stakingToken: string;
        _recoverTo: string;
        _poolAddress: string;
      }
    >;
  };

  estimateGas: {
    newPool(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "newPool(address,address,address,address)"(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    newPool(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "newPool(address,address,address,address)"(
      _token: string,
      _emitter: string,
      _stakingToken: string,
      _recoverTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
